package stream

import (
	"strings"
	"time"
)

type JsonID struct {
	ID int64 `json:"id"`
}

type Todo struct {
	UserID           int64    `json:"userId"`
	LoggedTimeStatus JsonID   `json:"loggedTimeStatus"`
	Date             DateOnly `json:"date"`
	Job              JsonID   `json:"job"`
	ItemUser         JsonID   `json:"jobItemUser"`
	Notes            string   `json:"notes"`
	Private          bool     `json:"private"`
}

// This type and code below generated by Gemini
type DateOnly time.Time

// Define the format constant
const dateLayout = "2006-01-02"

// MarshalJSON implements the json.Marshaler interface
func (d DateOnly) MarshalJSON() ([]byte, error) {
	return []byte(`"` + time.Time(d).Format(dateLayout) + `"`), nil
}

// nmarshalJSON implements the json.Unmarshaler interface
func (d *DateOnly) UnmarshalJSON(b []byte) error {
	s := strings.Trim(string(b), "\"")
	t, err := time.Parse(dateLayout, s)
	if err != nil {
		return err
	}
	*d = DateOnly(t)
	return nil
}
